version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: express-validator
    versions:
    - 6.10.0
    - 6.9.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: "@types/supertest"
    versions:
    - 2.0.10
  - dependency-name: handlebars
    versions:
    - 4.7.6
